name: filetobinary
description: "File To Binary - Binary To File"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^5.3.3
  path_provider: ^2.1.1
  open_file: ^3.3.1
  universal_html: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
